export const recipeList = [
  {
    id: 1,
    recipe: "Grilled Chicken Salad",
    servings: 4,
    calories: 320,
    reviews: 4,
    url: "https://example.com/grilled-chicken-salad",
    carbPer: 20,
    fatPer: 30,
    proteinPer: 50,
    cumulativeScore1: 0.345,
    cumulativeScore2: 0.456,
    nrf: 0.234,
    nrf2: 0.123,
    category: "Breakfast and Brunch",
  },
  {
    id: 2,
    recipe: "Vegetable Stir Fry",
    servings: 4,
    calories: 250,
    reviews: 4,
    url: "https://example.com/vegetable-stir-fry",
    carbPer: 35,
    fatPer: 15,
    proteinPer: 50,
    cumulativeScore1: 0.345,
    cumulativeScore2: 0.456,
    nrf: 0.234,
    nrf2: 0.123,
    category: "Breakfast and Brunch",
  },
  {
    id: 3,
    recipe: "Beef Tacos",
    servings: 4,
    calories: 450,
    reviews: 4,
    url: "https://example.com/beef-tacos",
    carbPer: 30,
    fatPer: 40,
    proteinPer: 30,
    cumulativeScore1: 0.345,
    cumulativeScore2: 0.456,
    nrf: 0.234,
    nrf2: 0.123,
    category: "Breakfast and Brunch",
  },
  {
    id: 4,
    recipe: "Quinoa and Black Beans",
    servings: 4,
    calories: 380,
    reviews: 4,
    url: "https://example.com/quinoa-black-beans",
    carbPer: 40,
    fatPer: 20,
    proteinPer: 40,
    cumulativeScore1: 0.345,
    cumulativeScore2: 0.456,
    nrf: 0.234,
    nrf2: 0.123,
    category: "Breakfast and Brunch",
  },
];
